# docker-compose.yml
# version: '3.8' # 이 줄은 제거하거나 주석 처리하는 것이 좋습니다 (경고 메시지 참고)

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    # Python 코드가 .env 파일을 직접 읽는 경우,
    # 이 옵션 대신 환경 변수를 사용하도록 코드를 수정해야 할 수도 있습니다.
    # 하지만 python-dotenv는 보통 환경 변수가 우선하므로 그대로 동작할 가능성이 높습니다.

  frontend: # <<< 프론트엔드 서비스 추가
    build: ./frontend
    ports:
      - "3000:3000" # Expose port 3000 for the frontend
    environment:
      # 브라우저가 접근 가능한 백엔드 주소로 변경
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend # 백엔드가 시작된 후 프론트엔드 시작 (네트워크 준비 보장)
    restart: unless-stopped # Optional: Add restart policy

networks:
  default:
    driver: bridge

volumes:
  storage_data: # Define named volume if not using bind mount 